database:
  image: mysql
  container_name: mysqldb
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: "beerdb"
    MYSQL_USER: "test"
    MYSQL_PASSWORD: "test"
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

